---
- name: Generate Deployer output for Tester
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: "Workaround RHBZ#1357579 - non-default region=regionOne"
        shell: "crudini --set ~/tempest-deployer-input.conf identity region regionOne"
        when: workarounds | bug('rhbz1357579')

      - name: fetch deployer output for tester
        fetch:
            src: "~/{{ item.src }}"
            dest: "{{ inventory_dir }}/{{ item.dest }}"
            flat: yes
        with_items:
            - src:  "overcloudrc"
              dest: "keystonerc"
            - src:  "tempest-deployer-input.conf"
              dest: "tempest-deployer-input.conf"
