- name: Check the release file
  hosts: controller:compute
  any_errors_fatal: true
  tasks:
        - shell: 'cat /etc/rhosp-release'
          register: rhosp_release
          when: "installer.product.version|openstack_release >= 10"

        - fail:
             msg: "The release string does not have the major version: {{installer.product.version }} not in {{ rhosp_release.stdout }}"
          when: "installer.product.version|openstack_release >= 10 and installer.product.version not in rhosp_release.stdout"
