- name: Creating compute scale script.
  shell: "cp -pv overcloud_deploy.sh overcloud_scale_compute.sh"

- name: change amount of scaled nodes
  replace:
      dest: "overcloud_scale_compute.sh"
      regexp: '^(\s*)--compute-scale\s\d\s\\'
      replace: '\1--compute-scale {{ scale_amount }} \\'

- name: change log file destination
  replace:
      dest: "overcloud_scale_compute.sh"
      regexp: '^(\s*)--log-file.*'
      replace: '\1--log-file overcloud_scale_compute.log'

- name: the compute scale overcloud script
  shell: "cat overcloud_scale_compute.sh"

- name: scaling overcloud
  shell: "bash ~/overcloud_scale_compute.sh"
  register: overcloud_scaling
  ignore_errors: yes

- name: print the last few lines of the output to spot failures
  shell: "tail -n30 overcloud_scale_compute.log"

- fail: msg="Overcloud scailing failed... :("
  when: overcloud_scaling.rc != 0
