- include: "internal_swift.yml"
  when: installer.storage.external != "yes"
  vars:
      storage_nodes: "{{ (installer.storage.nodes == None) |ternary([1, groups['ceph'] |default([])|length] | max, installer.storage.nodes) }}"

- name: prepare swift storage template
  template:
      src: "storage/swift.yml.j2"
      dest: "{{ template_base }}/swift.yaml"
      mode: 0755

- name: append the storage swift custom template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e {{ template_base }}/swift.yaml \'
