language: python
python:
    - "2.7"
# command to install dependencies
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install .
  - pip install pytest-random
  - cp infrared.cfg.example infrared.cfg
# command to run tests
script:
    - pep8 cli
    - pep8 tests
    - py.test tests -v --random
