libguestfs_fixed_version: 1.32.3-1
libguestfs_suffix: el7.x86_64.rpm
libguestfs_rpm_source: "{{ private.rpms.base_url }}"
libguestfs_packages:
      - libguestfs
      - libguestfs-tools-c
      - libguestfs-xfs
