---
- name: download the pre-built overcloud images
  get_url:
      dest: "~/{{ item }}"
      url: "{{ installer.images.url }}/{{ item }}"
  with_items: "{{ oii_images }}"

- name: untar the images
  shell: "tar -xvf ~/{{ item }}"
  with_items: "{{ oii_images }}"
