---
- name: Setup packstack on controller
  hosts: controller
  gather_facts: no
  sudo: yes
  vars:
      network_config: "{{ installer.network.config | default({}) }}"
      network_variant_config: "{{ installer.network.variant.config | default({}) }}"

      packstack_config: "{{ installer.config
          | combine(network_config)
          | combine(network_variant_config) }}"
  roles:
      - installer/packstack/install
