tar_files:
    '7':
        - "discovery-ramdisk.tar"
        - "deploy-ramdisk-ironic.tar"
        - "overcloud-full.tar"
    '8':
        - "ironic-python-agent.tar"
        - "overcloud-full.tar"

tar_images: "{{ tar_files[installer.product.version] }}"