---
- name: download the pre-built overcloud images
  get_url:
      dest: "~/{{ item }}"
      url: "{{ installer.images.url }}/{{ item }}"
  with_items: "{{ tar_images }}"
  register: command_result
  until: command_result.msg.find('OK' or 'file already exists' or 'All items completed') != -1
  retries: 40
  delay: 5

- name: untar the images
  unarchive:
      src: "~/{{ item }}"
      dest: "~/"
      copy: "no"
  with_items: "{{ tar_images }}"
