- name: append the swift storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '--swift-storage-scale {{ groups["swift"]| length }} \'

- name: append the swift storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '--swift-storage-flavor swift-{{ "swift" | to_uuid }} \'
