- name: prepare swift storage template
  template:
      src: "swift.yml.j2"
      dest: "{{ installer.overcloud.template_base }}/custom-swift.yaml"
      mode: 0755

- name: append the swift storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '--swift-storage-scale {{ groups["swift"]| length }} \'

- name: append the swift storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '--swift-storage-flavor swift-{{ "swift" | to_uuid }} \'

- name: append the storage swift custom template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e {{ installer.overcloud.template_base }}/custom-swift.yaml \'
