---

provisioner:
    hosts:
        host1:
            name: virthost
            ssh_host: !placeholder 'Address/FQDN of the BM hypervisor'
            ssh_user: root
            ssh_key_file: ~/.ssh/id_rsa
            groups:
                - virthost
