- name: create public VIP environment file
  template: src=public_vip.yaml.j2 dest={{ template_base }}/public_vip.yaml

- name: append the invocation line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e {{ template_base }}/public_vip.yaml \'

- name: append the invocation line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e /usr/share/openstack-tripleo-heat-templates/environments/tls-endpoints-public-ip.yaml \'
