- include: "hostname_schedular_hints.yml"
  when: installer.scheduler_hints|default(False)

- name: prepare hostname template
  vars:
    node_types:
        ceph:
            heat_name: CephStorage
            ospd_hostname: cephstorage
        swift:
            heat_name: ObjectStorage
            ospd_hostname: objectstorage
        compute:
            # As of Mitaka (9) upstream tripleo uses "novacompute"
            # According to BZ#1352057 this causes problems during upgrade.
            # RH-OSP reverted to use "compute" in all releases.
            # https://code.engineering.redhat.com/gerrit/#/c/78111
            # todo(yfried): Update this comment with proper RH-OSP doc once one is written
            # heat_name: NovaCompute
            # ospd_hostname: novacompute
            heat_name: Compute
            ospd_hostname: compute
        controller:
            heat_name: Controller
            ospd_hostname: controller
  template:
      src: "{{ installer.customized_hostnames |default('hostnames.yml.j2') }}"
      dest: "{{ template_base }}/hostnames.yml"
