---
- name: Get hostnames template
  stat:
      path: "{{ template_base }}/hostnames.yml"
  register: file_result

- include: "hostname_prepare_template.yml"
  when: not file_result.stat.exists

- name: append the hostnames template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '-e {{ template_base }}/hostnames.yml \'
