---
# Any step that should happen after the deployment of the overcloud playbook
# This could be validation of installation, etc
- name: Fetch key for SSH to the overcloud
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: fetch the private key file from the undercloud
        fetch:
            src: "~/.ssh/id_rsa"
            dest: "{{ inventory_dir }}/id_rsa_overcloud"
            flat: yes

- name: Generate ansible.ssh.config file
  hosts: localhost
  roles:
    - role: common/ansible-ssh-config
      asc_external_network: "{{ (installer.overcloud.network.isolation.enable == "yes")
        | ternary(installer.overcloud.network.template.content.parameter_defaults.ExternalNetCidr, '') }}"
      asc_virthost_ssh_key_file: "{{ provisioner.hosts.host1.ssh_key_file }}"
      asc_virthost_ssh_user: "{{ provisioner.hosts.host1.ssh_user }}"
      asc_virthost_ssh_host: "{{ provisioner.hosts.host1.ssh_host }}"
      asc_network_protocol: "{{ installer.overcloud.network.protocol }}"
      asc_inventory_dir: {{ inventory_dir }}

- name: Update the inventory file
  hosts: localhost
  gather_facts: no
  tasks:
      - name: update file permissions
        file:
            path: "{{ inventory_dir }}/id_rsa_overcloud"
            mode: 0600

      - name: Update Inventory
        add_host:
          name: "{{ item }}"
          ansible_ssh_user: "heat-admin"
        with_items: groups['openstack_nodes'] | difference(["undercloud"])

      - name: Generate new Inventory file
        template:
          dest: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
          src: "{{ inventory_dir }}/templates/inventory.j2"

      - name: Link to new Inventory file
        file:
          dest: "{{ lookup('env', 'PWD') }}/hosts"
          state: link
          src: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
