---
- name: Configure tempest
  hosts: tester
  gather_facts: yes
  pre_tasks:
      - name: copy the keystonerc to the tester
        copy:
            src: "{{ inventory_dir }}/keystonerc"
            dest: "~/keystonerc"

      - name: copy the tempest-deployer-input.conf to the tester in case it exists
        copy:
            src: "{{ inventory_dir }}/tempest-deployer-input.conf"
            dest: "~/tempest-deployer-input.conf"
        register: deployer_input_result
        ignore_errors: yes

      # (TODO) This shouldn't be here according afazekas, but it's required to
      # run tempest
      - name: Create heat_stack_owner
        # todo(yfried): convert to built-in
        shell: "source ~/keystonerc; openstack role create heat_stack_owner"
        when: installer.type == "ospd"
        ignore_errors: yes
  roles:
      - {role: tester/tempest/setup/git, when: tester.setup.type == "git"}
      - {role: tester/tempest/setup/rpm, when: tester.setup.type == "rpm"} #WIP
