- name: Update undercloud for ovb
  tags: ovb
  hosts: undercloud
  become: yes
  become_method: sudo
  any_errors_fatal: true
  vars:
      # todo(obaranov) dynamically get/read from settings the ipmi interface name
      ipmi_interface: "eth0"
  tasks:
      - name: Set MTU values
        shell: >
          ip link set {{ ipmi_interface }} mtu 1450;
          echo "MTU=1450" >> /etc/sysconfig/network-scripts/ifcfg-{{ item }}
        with_items:
          - "{{ ipmi_interface }}"

      - name: Ensure neutron will use needed MTU
        lineinfile: dest="/etc/dnsmasq-ironic.conf" line="dhcp-option-force=26,1450"

      - name: Restart neutron and ironic services
        service:
            name: "{{ item }}"
            state: restarted
        with_items:
            - "openstack-ironic-conductor"
            - "neutron-server.service"
            - "neutron-openvswitch-agent.service"
            - "neutron-dhcp-agent.service"

- name: change quotas
  tags: ovb
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  any_errors_fatal: true
  tasks:
    - name: set neutron subnet quota to unlimited
      ignore_errors: true
      shell: >
        source ~/stackrc;
        neutron quota-update --subnet -1;
        neutron quota-update --network -1;
        neutron quota-update --security_group -1;
