---
# Any step that should happen after the deployment of the osp-d playbook
# This could be create ssh forwarding to the nodes, validation of installation, etc
- name: Post tasks
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: Copy the keystonerc file for the tester
        fetch:
            src: "~/overcloudrc"
            dest: "{{ inventory_dir }}/keystonerc"
            flat: yes

- name: Apply workarounds if necessary
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  roles:
      - {role: workarounds/rhbz1304367, when: workarounds.rhbz1304367 is defined and 'ceph' in groups }
#  tasks:
#      # TODO: Move to role
#      - name: Get the controller nodes IPs
#        shell: "source ~/stackrc; nova list | awk '/controller/ {print $12}' | grep -oP '[0-9.]+'"
#        register: ip_list
#
#      - name: Workaround for Controllers
#        shell: "ssh -o StrictHostKeyChecking=no -l heat-admin {{ item }} 'sudo crudini  --set /etc/swift/container-server.conf app:container-server allow_versions true'"
#        with_items: ip_list.stdout_lines
#
#      - name: restart swift
#        shell: "ssh -o StrictHostKeyChecking=no -l heat-admin {{ item }} 'sudo systemctl restart openstack-swift*'"

#TODO: remove this when the templating system is in place
- name: External network creation
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: create the external network
        shell: "source ~/overcloudrc; neutron net-create nova --router:external --provider:physical_network datacentre --provider:network_type flat"

      - name: create the external subnet
        shell: "source ~/overcloudrc; neutron subnet-create nova 192.168.1.0/24 --name external_subnet --enable-dhcp=False --allocation-pool start=192.168.1.210,end=192.168.1.250 --gateway 192.168.1.1"

#TODO: remove this when tester is in place
- name: Setup and run tempest
  hosts: undercloud
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: create role heat_stack_owner
        shell: "source ~/overcloudrc; keystone role-create --name heat_stack_owner"

      - name: create the tempest dir
        shell: "mkdir tempest-dir"

      - name: setup the tempest-dir
        shell: "/usr/share/openstack-tempest-{{ product.version.code_name }}/tools/configure-tempest-directory"
        args:
            chdir: "~/tempest-dir"

      - name: run tempest configuration tool
        shell: "source ~/overcloudrc; tools/config_tempest.py --deployer-input ~/tempest-deployer-input.conf --debug --create identity.uri $OS_AUTH_URL identity.admin_password $OS_PASSWORD"
        args:
            chdir: "~/tempest-dir"

      - name: run tempest
        shell: "tools/run-tests.sh --parallel --concurrency 8 &> tempest_run.log"
        args:
            chdir: "~/tempest-dir"
        ignore_errors: yes

      - name: print last 30 lines of tempest run for status
        shell: "tail -n30 tempest_run.log"
        args:
            chdir: "~/tempest-dir"

      - name: fetch tempest result
        fetch:
            src: "~/tempest-dir/tempest.xml"
            dest: "{{ lookup('env', 'PWD') }}/nosetests.xml"
            flat: yes
