---
# Any step that should happen after the deployment of the osp-d playbook
# This could be create ssh forwarding to the nodes, validation of installation, etc
- name: Post tasks
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  roles:
      - {role: workarounds/rhbz1302047, when: workarounds.rhbz1302047 is defined }
      - {role: workarounds/rhbz1217093, when: workarounds.rhbz1217093 is defined }
      - {role: workarounds/rhbz1314732, when: workarounds.rhbz1314732 is defined }
      - {role: workarounds/rhbz1291568, when: workarounds.rhbz1291568 is defined and 'ceph' in groups }
      - {role: workarounds/rhbz1304367, when: workarounds.rhbz1304367 is defined and 'ceph' in groups }
      - {role: workarounds/rhbz1314725, when: workarounds.rhbz1314725 is defined }
#      - TODO: https://bugzilla.redhat.com/show_bug.cgi?id=1233251
  tasks:
      - name: Copy the keystonerc file for the tester
        fetch:
            src: "~/overcloudrc"
            dest: "{{ inventory_dir }}/keystonerc"
            flat: yes

      - name: Copy the tempest-deployer-input.conf file for the tester
        fetch:
            src: "~/tempest-deployer-input.conf"
            dest: "{{ inventory_dir }}/tempest-deployer-input.conf"
            flat: yes

#TODO: remove this when the templating system is in place
- name: External network creation
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: get the default floating ip pool name as set in the nova.conf file
        shell: "sudo grep -oP '(?<=default_floating_pool=)(.*$)' /etc/nova/nova.conf"
        register: pool_name

      - name: create the external network
        shell: "source ~/overcloudrc; neutron net-create {{ pool_name.stdout_lines|last }} --router:external --provider:physical_network datacentre --provider:network_type flat"

      - name: create the external subnet
        shell: "source ~/overcloudrc; neutron subnet-create {{ pool_name.stdout_lines|last }} 192.168.1.0/24 --name external_subnet --enable-dhcp=False --allocation-pool start=192.168.1.210,end=192.168.1.250 --gateway 192.168.1.1"
