---
# Any step that should happen after the deployment of the osp-d playbook
# This could be create ssh forwarding to the nodes, validation of installation, etc
- name: Post tasks
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: Copy the keystonerc file for the tester
        fetch:
            src: "~/overcloudrc"
            dest: "{{ inventory_dir }}/keystonerc"
            flat: yes

- name: Apply workarounds if necessary
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  roles:
      - {role: workarounds/rhbz1304367, when: workarounds.rhbz1304367 is defined and 'ceph' in groups }

#TODO: remove this when the templating system is in place
- name: External network creation
  hosts: undercloud
  gather_facts: no
  become: yes
  become_user: "{{ installer.user.name }}"
  tasks:
      - name: create the external network
        shell: "source ~/overcloudrc; neutron net-create nova --router:external --provider:physical_network datacentre --provider:network_type flat"

      - name: create the external subnet
        shell: "source ~/overcloudrc; neutron subnet-create nova 192.168.1.0/24 --name external_subnet --enable-dhcp=False --allocation-pool start=192.168.1.210,end=192.168.1.250 --gateway 192.168.1.1"
