---
- name: download the pre-built overcloud images
  get_url:
      dest: "~/{{ item.value }}"
      url: "{{ installer.overcloud.images.url }}/{{ item.value }}"
  with_dict: "{{ installer.overcloud.images.files }}"

- name: untar the images
  shell: "tar -xvf ~/{{ item.value }}"
  with_dict: "{{ installer.overcloud.images.files }}"

- name: install the libguestfs-tools to customize the image
  shell: "sudo yum install libguestfs-tools -y"

- name: list the available images
  shell: "ls ~/*.qcow2"
  register: image_list

- name: assign a default password for root
  shell: "virt-customize -a {{ item }} --root-password password:redhat"
  with_items: image_list.stdout_lines