---
- name: ensure wget is installed
  yum:
      name: wget
      state: latest

- name: download the pre-built overcloud images
  shell: >
        wget --quiet -c -O ~/{{ item.value }}
        "{{ installer.overcloud.images.server }}/{{ item.value }}"
  with_dict: "{{ installer.overcloud.images }}"

- name: untar the images
  shell: "tar -xvf ~/{{ item.value }}"
  with_dict: "{{ installer.overcloud.images.files }}"
