---
- name: Change key file permissions
  hosts: localhost
  gather_facts: no
  tasks:
    - file:
        path: "{{ provisioner.key_file }}"
        state: touch
        mode: 0600
      when: provisioner.key_file is defined

- name: clean old inventory file
  hosts: localhost
  gather_facts: no
  tasks:
    - file:
        dest: "{{ lookup('env', 'PWD') }}/hosts"
        state: link
        src: "{{ lookup('env', 'PWD') }}/local_hosts"

  # todo remove that workaround
- name: Add host to host list
  hosts: localhost
  gather_facts: no
  tasks:
      - name: add hosts to host list
        add_host:
            name: "{{ provisioner.host.name }}"
            groups: "{{ provisioner.host.groups| join(',') }}"
            node_label: "virthost"
            ansible_ssh_user: "{{ provisioner.host.user }}"
            ansible_ssh_host: "{{ provisioner.host.address }}"
            ansible_ssh_private_key_file: "{{ provisioner.host.key }}"
#- include: "provisioner/{{ provisioner.type }}/main.yml"
#
#- name: generate inventory file
#  hosts: localhost
#  gather_facts: no
#  tasks:
#    - template:
#        dest: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
#        src: "{{ inventory_dir }}/templates/inventory.j2"
#
#    - file:
#        dest: "{{ lookup('env', 'PWD') }}/hosts"
#        state: link
#        src: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
- name: Import urls for nodes and create vms
  hosts: virthost
  gather_facts: no
  roles:
    - { role: provisioner/virsh/images/import, node_name: "undercloud" }
