---
- name: Change key file permissions
  hosts: localhost
  gather_facts: no
  tasks:
    - file:
        path: "{{ provisioner.key_file }}"
        state: touch
        mode: 0600
      when: provisioner.key_file is defined

- name: clean old inventory file
  hosts: localhost
  gather_facts: no
  tasks:
    - file:
        dest: "{{ lookup('env', 'PWD') }}/hosts"
        state: link
        src: "{{ lookup('env', 'PWD') }}/local_hosts"

- include: provisioner/{{ provisioner.type }}/main.yml

- name: generate inventory file
  hosts: localhost
  gather_facts: no
  tasks:
    - template:
        dest: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"
        src: provisioner/templates/inventory.j2
    - file:
        dest: "{{ lookup('env', 'PWD') }}/hosts"
        state: link
        src: "{{ lookup('env', 'PWD') }}/hosts-{{ lookup('env', 'USER') }}"

- name: extend hosts file
  hosts: openstack_nodes
  gather_facts: no
  sudo: yes
  tasks:
    - name: Template of nodes
      template:
        dest: "/tmp/ansible_hosts"
        src: provisioner/templates/hosts.j2
      register: templatehosts
      when: provisioner.network.domain is defined

    - name: Update hosts file
      shell: "cat /tmp/ansible_hosts >> /etc/hosts"
      when: templatehosts|changed

- name: Break point
  hosts: localhost
  tasks:
      - fail:
            msg: "Stopping after provisioning per user request"
        when: break is defined and break == "after_provision"