- name: prepare ceph storage template
  template:
      src: "ceph.yml.j2"
      dest: "{{ installer.overcloud.template_base }}/custom-ceph.yaml"
      mode: 0755

- name: append our params to the storage template file
  shell: "cat {{ installer.overcloud.template_base }}/custom-ceph.yaml >> {{ installer.overcloud.template_base }}/environments/storage-environment.yaml"

- name: append the ceph storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '                       --ceph-storage-scale {{ groups["ceph"]| length }} \\'

- name: append the ceph storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '                       --ceph-storage-flavor ceph \\'

- name: append the storage template line to the base overcloud deploy script
  lineinfile:
      dest: "~/overcloud_deploy.sh"
      line: '                       -e {{ installer.overcloud.template_base }}/environments/storage-environment.yaml \\'
